// src/components/CourtCard.vue
<script setup lang="ts">
import { ref } from 'vue';
import type { Venue, Language } from '../../types';

const props = defineProps<{
  venue: Venue;
  onClick: () => void;
  language: Language;
  t: (key: string) => string;
  darkMode: boolean;
  isSaved: boolean;
  onToggleSave: () => void;
  isMobile?: boolean;
}>();

const isExpanded = ref(false);

const toggleExpand = (e: MouseEvent) => {
  e.stopPropagation();
  isExpanded.value = !isExpanded.value;
};
</script>

<template>
  <div v-if="isMobile">
    <div
      class="border rounded-[16px] overflow-hidden mb-4 transition-all duration-300 shadow-sm"
      :class="darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-100'"
    >
      <div
        class="flex items-center p-4 cursor-pointer gap-4"
        @click="onClick"
      >
        <div class="w-16 h-16 rounded-[16px] overflow-hidden flex-shrink-0">
          <img
            :src="venue.images[0] || 'https://via.placeholder.com/150'"
            class="w-full h-full object-cover"
            alt=""
          />
        </div>
        <div class="flex-1 min-w-0">
          <h3
            class="font-[900] text-[24px] leading-tight truncate"
            :class="darkMode ? 'text-white' : 'text-gray-900'"
          >
            {{ venue.name }}
          </h3>
          <p
            class="text-[14px] font-[400] opacity-70"
            :class="darkMode ? 'text-gray-400' : 'text-gray-500'"
          >
            🚇 {{ venue.mtrStation }}
          </p>
        </div>
        <button
          class="p-2 rounded-full transition-transform"
          :class="[isExpanded ? 'rotate-180' : '', darkMode ? 'bg-gray-700' : 'bg-gray-50']"
          @click.stop="toggleExpand"
        >
          ▼
        </button>
      </div>

      <div
        v-if="isExpanded"
        class="px-4 pb-4 animate-in slide-in-from-top duration-200"
      >
        <div
          class="flex items-center gap-3 text-[12px] font-[400] mb-3"
          :class="darkMode ? 'text-gray-400' : 'text-gray-500'"
        >
          <span>🚶 {{ venue.walkingDistance }} {{ t('min') }}</span>
          <span>⬆️ {{ venue.ceilingHeight }}m</span>
          <span class="ml-auto font-[900] text-[#007a67] text-[16px]">
            ${{ venue.startingPrice }}/hr
          </span>
        </div>
        <div class="flex gap-2">
          <button
            class="flex-1 py-2.5 rounded-[8px] font-bold text-xs flex items-center justify-center gap-2 transition-all"
            :class="isSaved ? 'bg-red-500 text-white' : 'bg-gray-100 dark:bg-gray-700 text-gray-500'"
            @click.stop="onToggleSave"
          >
            {{ isSaved ? '❤️ Saved' : '🤍 Save' }}
          </button>
          <button
            class="flex-[2] py-2.5 bg-[#007a67] text-white rounded-[8px] font-[900] text-xs shadow-md"
            @click="onClick"
          >
            {{ t('viewDetails') }}
          </button>
        </div>
      </div>
    </div>
  </div>

  <div
    v-else
    class="group cursor-pointer rounded-[16px] overflow-hidden border transition-all duration-300 hover:shadow-2xl"
    :class="darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-100'"
    @click="onClick"
  >
      <div class="relative h-44 overflow-hidden">
      <img
        :src="venue.images[0]"
        :alt="venue.name"
        class="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700"
      />
      <div class="absolute top-2 right-2">
        <button
          class="p-2.5 rounded-full shadow-lg transition-all active:scale-90 rounded-[999px]"
          :class="isSaved ? 'bg-red-500 text-white' : 'bg-white/90 text-gray-500'"
          @click.stop="onToggleSave"
        >
          {{ isSaved ? '❤️' : '🤍' }}
        </button>
      </div>
    </div>

    <div class="p-4">
      <h3
        class="font-[900] text-[24px] leading-tight truncate mb-2"
        :class="darkMode ? 'text-white' : 'text-gray-900'"
      >
        {{ venue.name }}
      </h3>
      <div
        class="flex items-center gap-3 text-[14px] font-[400] mb-4"
        :class="darkMode ? 'text-gray-400' : 'text-gray-500'"
      >
        <span>🚇 {{ venue.mtrStation }}</span>
        <span>🚶 {{ venue.walkingDistance }} {{ t('min') }}</span>
      </div>
      <div class="flex items-center justify-between">
        <span class="text-[24px] font-[900] text-[#007a67]">
          ${{ venue.startingPrice }}
        </span>
        <button
          class="px-4 py-2 bg-[#007a67] text-white rounded-[8px] font-bold text-sm shadow-md group-hover:brightness-110 rounded-[8px]"
          @click.stop="onClick"
        >
          {{ t('viewDetails') }}
        </button>
      </div>
    </div>
  </div>
</template>

// components/CourtCard.tsx

import React, { useState } from 'react';
import { Venue, Language } from '../types';

interface CourtCardProps {
    venue: Venue;
    onClick: () => void;
    language: Language;
    t: (key: string) => string;
    darkMode: boolean;
    isSaved: boolean;
    onToggleSave: () => void;
    isMobile?: boolean;
}

const CourtCard: React.FC<CourtCardProps> = ({ venue, onClick, language, t, darkMode, isSaved, onToggleSave, isMobile }) => {
    const [isExpanded, setIsExpanded] = useState(false);

    const toggleExpand = (e: React.MouseEvent) => {
        e.stopPropagation();
        setIsExpanded(!isExpanded);
    };

    if (isMobile) {
        return (
            <div className={`border rounded-2xl overflow-hidden mb-4 transition-all duration-300 shadow-sm ${darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-100'}`}>
                <div className="flex items-center p-4 cursor-pointer gap-4" onClick={onClick}>
                    <div className="w-16 h-16 rounded-xl overflow-hidden flex-shrink-0">
                        <img src={venue.images[0] || 'https://via.placeholder.com/150'} className="w-full h-full object-cover" alt="" />
                    </div>
                    <div className="flex-1 min-w-0">
                        <h3 className={`font-black text-sm md:text-base leading-tight truncate ${darkMode ? 'text-white' : 'text-gray-900'}`}>{venue.name}</h3>
                        <p className={`text-[10px] uppercase opacity-50 ${darkMode ? 'text-gray-400' : 'text-gray-500'}`}>🚇 {venue.mtrStation}</p>
                    </div>
                    <button onClick={toggleExpand} className={`p-2 rounded-full transition-transform ${isExpanded ? 'rotate-180' : ''} ${darkMode ? 'bg-gray-700' : 'bg-gray-50'}`}>▼</button>
                </div>

                {isExpanded && (
                    <div className="px-4 pb-4 animate-in slide-in-from-top duration-200">
                        <div className={`flex items-center gap-3 text-[11px] mb-3 ${darkMode ? 'text-gray-400' : 'text-gray-500'}`}>
                            <span>🚶 {venue.walkingDistance} {t('min')}</span>
                            <span>⬆️ {venue.ceilingHeight}m</span>
                            <span className="ml-auto font-black text-[#00e911] text-sm">${venue.startingPrice}/hr</span>
                        </div>
                        <div className="flex gap-2">
                             <button onClick={(e) => { e.stopPropagation(); onToggleSave(); }} className={`flex-1 py-2.5 rounded-xl font-bold text-xs flex items-center justify-center gap-2 transition-all ${isSaved ? 'bg-red-500 text-white' : 'bg-gray-100 dark:bg-gray-700 text-gray-500'}`}>
                                {isSaved ? '❤️ Saved' : '🤍 Save'}
                            </button>
                            <button onClick={onClick} className="flex-[2] py-2.5 bg-[#00e911] text-white rounded-xl font-black text-xs shadow-md">{t('viewDetails')}</button>
                        </div>
                    </div>
                )}
            </div>
        );
    }

    return (
        <div onClick={onClick} className={`group cursor-pointer rounded-2xl overflow-hidden border transition-all duration-300 hover:shadow-2xl ${darkMode ? 'bg-gray-800 border-gray-700' : 'bg-white border-gray-100'}`}>
            <div className="relative h-44 overflow-hidden">
                <img src={venue.images[0]} alt={venue.name} className="w-full h-full object-cover group-hover:scale-110 transition-transform duration-700" />
                <div className="absolute top-2 right-2">
                    <button onClick={(e) => { e.stopPropagation(); onToggleSave(); }} className={`p-2.5 rounded-full shadow-lg transition-all active:scale-90 ${isSaved ? 'bg-red-500 text-white' : 'bg-white/90 text-gray-500'}`}>
                        {isSaved ? '❤️' : '🤍'}
                    </button>
                </div>
            </div>
            
            <div className="p-4">
                <h3 className={`font-black text-lg leading-tight truncate mb-2 ${darkMode ? 'text-white' : 'text-gray-900'}`}>{venue.name}</h3>
                <div className={`flex items-center gap-3 text-xs mb-4 ${darkMode ? 'text-gray-400' : 'text-gray-500'}`}>
                    <span>🚇 {venue.mtrStation}</span>
                    <span>🚶 {venue.walkingDistance} {t('min')}</span>
                </div>
                <div className="flex items-center justify-between">
                    <span className="text-xl font-black text-[#00e911]">${venue.startingPrice}</span>
                    <button className="px-4 py-2 bg-[#00e911] text-white rounded-xl font-bold text-sm shadow-md group-hover:brightness-110">{t('viewDetails')}</button>
                </div>
            </div>
        </div>
    );
};

export default CourtCard;
