// src/components/MobileVenueCard.tsx
import React from 'react';
import { Venue, Language } from '../../types.ts';

interface MobileVenueCardProps {
    venue: Venue;
    language: Language;
    t: (key: string) => string;
    darkMode: boolean;
    isSaved: boolean;
    onToggleSave: () => void;
    onViewDetails: () => void;
}

const MobileVenueCard: React.FC<MobileVenueCardProps> = ({ venue, language, t, darkMode, isSaved, onToggleSave, onViewDetails }) => {
    const handleWhatsApp = () => {
        const message = encodeURIComponent(
            language === 'en' 
                ? `Hi, I'm interested in booking ${venue.name}. Could you please let me know about availability?`
                : `你好，我想預訂${venue.name}，請問有時間嗎？`
        );
        window.open(`https://wa.me/${venue.whatsapp.replace(/[^0-9]/g, '')}?text=${message}`, '_blank');
    };

    return (
        <div className="p-5 pt-0">
            <div className="mb-4 pr-14">
                <h2 className={`text-[24px] font-[900] leading-tight mb-2 ${darkMode ? 'text-white' : 'text-gray-900'}`}>
                    {venue.name}
                </h2>
                <div className="flex flex-col gap-1">
                    <div className={`text-[12px] font-[400] ${darkMode ? 'text-gray-400' : 'text-gray-500'}`}>
                        🚇 {venue.mtrStation}
                    </div>
                    <div className="flex items-center gap-1.5 mt-0.5">
                        <span className="text-[20px] font-[900] text-[#007a67]">
                            ${venue.startingPrice}
                        </span>
                        <span className="text-[12px] font-[700] opacity-60 uppercase">
                            /{language === 'en' ? 'hr' : '小時'}
                        </span>
                    </div>
                </div>
            </div>

            <div className="flex flex-col gap-3 mb-6">
                <button 
                    onClick={onViewDetails} 
                    className={`w-full px-4 py-3.5 border-2 rounded-[8px] font-[900] text-sm shadow-sm transition-all active:scale-[0.98] ${darkMode ? 'bg-gray-800 border-gray-700 text-white active:bg-gray-700' : 'bg-white border-gray-100 text-gray-900 active:bg-gray-50'}`}
                >
                    {t('viewDetails')}
                </button>
                <button 
                    onClick={handleWhatsApp} 
                    className="w-full px-4 py-3.5 rounded-[8px] text-white font-[900] text-sm shadow-lg transition-all active:scale-[0.98] flex items-center justify-center gap-2" 
                    style={{ background: '#007a67' }}
                >
                    <span>💬</span> {t('bookNow')}
                </button>
            </div>

            <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
                <div className="relative overflow-hidden rounded-[16px] shadow-lg border dark:border-gray-800">
                    <img src={venue.images[0]} alt={venue.name} className="w-full h-48 object-cover" />
                    <button 
                        onClick={(e) => { e.stopPropagation(); onToggleSave(); }} 
                        className={`absolute top-3 right-3 p-2.5 rounded-full shadow-lg transition-all active:scale-90 ${isSaved ? 'bg-red-500 text-white' : 'bg-white/90 text-gray-500'}`}
                    >
                        {isSaved ? '❤️' : '🤍'}
                    </button>
                </div>

                <div className={`text-[14px] font-[400] leading-relaxed px-1 ${darkMode ? 'text-gray-400' : 'text-gray-600'}`}>
                    {venue.description || "Perfect venue for competitive or casual pickleball sessions. Fully equipped and conveniently located near the MTR."}
                </div>
                
                <div className={`p-4 rounded-[12px] border text-[12px] font-[700] flex justify-between items-center ${darkMode ? 'bg-gray-800 border-gray-700 text-gray-400' : 'bg-gray-50 border-gray-100 text-gray-500'}`}>
                    <span className="flex items-center gap-1">🚶 {venue.walkingDistance} {t('min')} {t('walk')}</span>
                    <span className="flex items-center gap-1">🏢 {t('ceilingHeight')}: {venue.ceilingHeight}m</span>
                </div>
            </div>
        </div>
    );
};

export default MobileVenueCard;

// src/components/MobileVenueCard.vue
<script setup lang="ts">
import type { Venue, Language } from '../../types';

const props = defineProps<{
  venue: Venue;
  language: Language;
  t: (key: string) => string;
  darkMode: boolean;
  isSaved: boolean;
  onToggleSave: () => void;
  onViewDetails: () => void;
}>();
</script>

<template>
  <button
    type="button"
    class="w-full text-left"
    @click="onViewDetails"
  >
    <div
      class="flex items-center gap-4 px-4 py-3 shadow-sm transition-all active:scale-[0.98]"
      :class="darkMode ? 'bg-gray-900 border-gray-800' : 'bg-white border-gray-200'"
    >
      <div class="w-20 h-20 rounded-[16px] overflow-hidden flex-shrink-0 bg-gray-200 dark:bg-gray-700">
        <img
          :src="venue.images[0] || 'https://via.placeholder.com/150'"
          :alt="venue.name"
          class="w-full h-full object-cover"
        />
      </div>

      <div class="flex-1 min-w-0">
        <h3
          class="text-[18px] font-[900] leading-tight truncate mb-1"
          :class="darkMode ? 'text-white' : 'text-gray-900'"
        >
          {{ venue.name }}
        </h3>
        <p
          class="text-[13px] font-[400] truncate"
          :class="darkMode ? 'text-gray-400' : 'text-gray-500'"
        >
          🚇 {{ venue.mtrStation }}
        </p>
        <div class="flex items-center gap-2 mt-1 text-[12px]">
          <span :class="darkMode ? 'text-gray-400' : 'text-gray-500'">
            🚶 {{ venue.walkingDistance }} {{ t('min') }}
          </span>
        </div>
        <div class="flex items-baseline gap-1 mt-2">
          <span class="text-[18px] font-[900] text-[#007a67]">
            ${{ venue.startingPrice }}
          </span>
          <span class="text-[11px] font-[700] opacity-60 uppercase">
            /{{ language === 'en' ? 'hr' : '小時' }}
          </span>
        </div>
      </div>

      <div class="self-start">
        <button
          type="button"
          class="p-2 rounded-full shadow-sm transition-all active:scale-90"
          :class="isSaved ? 'bg-red-500 text-white' : (darkMode ? 'bg-gray-800 text-gray-300' : 'bg-gray-100 text-gray-500')"
          @click.stop="onToggleSave"
        >
          {{ isSaved ? '❤️' : '🤍' }}
        </button>
      </div>
    </div>
  </button>
</template>
